# Generated by Django 2.2.7 on 2020-08-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
