# Generated by Django 2.2.7 on 2020-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20200825_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='fc',
            field=models.DateTimeField(),
        ),
    ]
