# Generated by Django 2.2.7 on 2020-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_auto_20200826_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='fc',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
