# Generated by Django 2.2.7 on 2020-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_auto_20200826_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
