# Generated by Django 2.2.7 on 2020-09-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='foto',
            field=models.ImageField(default=-2018, upload_to=''),
            preserve_default=False,
        ),
    ]
