# Generated by Django 2.2.7 on 2020-10-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_auto_20201007_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
