# Generated by Django 2.2.7 on 2020-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_autor_categorialibro_lector_libro_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(),
        ),
    ]
