# Generated by Django 2.2.7 on 2020-10-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_auto_20201019_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
