# Generated by Django 2.2.7 on 2020-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_prestamo_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='stok',
        ),
        migrations.AddField(
            model_name='libro',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
