# Generated by Django 2.2.7 on 2020-09-28 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0007_categorias_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo Producto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('impuesto', models.BooleanField(default=False, verbose_name='ISV 15')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.Categorias')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Productos Agregados',
                'verbose_name_plural': 'Mis Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Producto_Imagen', to='inventario.Producto')),
            ],
        ),
    ]
