# Generated by Django 2.2.7 on 2020-09-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=0.0015401540154015402, upload_to=''),
            preserve_default=False,
        ),
    ]
