# Generated by Django 2.2.7 on 2020-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_acercade'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Existencia Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Codigo Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre Producto'),
        ),
    ]
