# Generated by Django 2.2.7 on 2020-10-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_carritocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
    ]
