# Generated by Django 2.2.7 on 2020-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20201009_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompra',
            name='isv',
            field=models.FloatField(default=0.0006435643564356436, verbose_name='Impuesto'),
            preserve_default=False,
        ),
    ]
