# Generated by Django 2.2.7 on 2020-10-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_carritocompra_isv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='isv',
            field=models.FloatField(blank=True, null=True, verbose_name='Impuesto'),
        ),
    ]
