# Generated by Django 2.2.7 on 2020-10-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20201019_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_car', models.PositiveIntegerField()),
            ],
        ),
    ]
